CREATE TABLE order_create_time
(
    order_sn STRING NOT NULL,
    region STRING NOT NULL,
    currency STRING NOT NULL,
    cod BOOL NOT NULL,
    total_amount NUMERIC NOT NULL,
    order_status STRING NOT NULL,
    shipping_carrier STRING NOT NULL,
    payment_method STRING NOT NULL,
    estimated_shipping_fee NUMERIC NOT NULL,
    message_to_seller STRING,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    days_to_ship SMALLINT NOT NULL,
    ship_by_date INT NOT NULL,
    buyer_user_id INT NOT NULL,
    buyer_username STRING NOT NULL,
    recipient_address STRUCT<
        name STRING NOT NULL,
        phone STRING,
        town STRING,
        district STRING,
        city STRING,
        state STRING,
        region STRING,
        zipcode STRING,
        full_address STRING
    >,
    actual_shipping_fee NUMERIC,
    goods_to_declare BOOL,
    seller_note STRING,
    seller_note_update_time TIMESTAMP,
    items ARRAY<STRUCT<
        item_id INT,
        item_name STRING,
        item_sku STRING,
        model_id INT,
        model_name STRING,
        modeL_sku STRING,
        model_quantity_purchased INT,
        model_original_price NUMERIC,
        model_discounted_price NUMERIC,
        wholesale BOOL,
        weight NUMERIC,
        add_on_deal BOOL,
        main_item BOOL,
        add_on_deal_id INT,
        promotion_type STRING,
        promotion_id INT,
        order_item_id INT,
        promotion_group_id INT,
        image_info STRUCT<
            image_url STRING
        >
    >>,
    pay_time TIMESTAMP,
    dropshipper STRING,
    dropshipper_phone STRING,
    split_up BOOL,
    buyer_cancel_reason STRING,
    cancel_by STRING,
    cancel_reason STRING,
    actual_shipping_fee_confirmed BOOL,
    fulfillment_flag STRING,
    pickup_done_time TIMESTAMP,
    invoice_data STRUCT<
        number STRING,
        series_number STRING,
        access_key STRING,
        issue_date TIMESTAMP,
        total_value NUMERIC,
        products_total_value NUMERIC,
        tax_code STRING
    >,
    checkout_shipping_carrier STRING,
    reverse_shipping_fee NUMERIC,
    escrow STRUCT<
        escrow_amount NUMERIC,
        buyer_total_amount NUMERIC,
        original_price NUMERIC,
        seller_discount NUMERIC,
        shopee_discount NUMERIC,
        voucher_from_seller NUMERIC,
        coins NUMERIC,
        buyer_paid_shipping_fee NUMERIC,
        buyer_transaction_fee NUMERIC,
        cross_border_tax NUMERIC,
        payment_promotion NUMERIC,
        commission_fee NUMERIC,
        service_fee NUMERIC,
        seller_transaction_fee NUMERIC,
        seller_lost_compensation NUMERIC,
        seller_coin_cash_back NUMERIC,
        escrow_tax NUMERIC,
        final_shipping_fee NUMERIC,
        actual_shipping_fee NUMERIC,
        shopee_shipping_rebate NUMERIC,
        shipping_fee_discount_from_3pl NUMERIC,
        seller_shipping_discount NUMERIC,
        estimated_shipping_fee NUMERIC,
        seller_voucher_code ARRAY<STRING>,
        drc_adjustable_fund NUMERIC,
        cost_of_goods_sold NUMERIC,
        original_cost_of_goods_sold NUMERIC,
        original_shopee_discount NUMERIC,
        seller_return_refund NUMERIC,
        escrow_amount_pri NUMERIC,
        buyer_total_amount_pri NUMERIC,
        original_price_pri NUMERIC,
        seller_return_refund_pri NUMERIC,
        commission_fee_pri NUMERIC,
        service_fee_pri NUMERIC,
        drc_adjustable_refund_pri NUMERIC,
        pri_currency STRING,
        aff_currency STRING,
        exchange_rate NUMERIC,
        reverse_shipping_fee NUMERIC
    >
)
PARTITION BY DATE(create_time)